version: "2"

services:

    traefik:
        image: "traefik:v1.7"
        container_name: "traefik"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "$PWD/traefik/traefik.toml:/traefik.toml"
            - "$PWD/traefik/acme.json:/acme.json"
        restart: unless-stopped

    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            # Explicitly tell Traefik to expose this container
            - "traefik.enable=true"

            # Overrides the default frontend rule.
            # Default:
            #   Host:{containerName}.{domain} or
            #   Host:{service}.{project_name}.{domain} if you are using docker-compose.
            - "traefik.frontend.rule=Host:localhost"
